/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const FactsLazyImport = createFileRoute('/facts')()
const AgesLazyImport = createFileRoute('/ages')()

// Create/Update Routes

const FactsLazyRoute = FactsLazyImport.update({
  path: '/facts',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/facts.lazy').then((d) => d.Route))

const AgesLazyRoute = AgesLazyImport.update({
  path: '/ages',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ages.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ages': {
      preLoaderRoute: typeof AgesLazyImport
      parentRoute: typeof rootRoute
    }
    '/facts': {
      preLoaderRoute: typeof FactsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AgesLazyRoute,
  FactsLazyRoute,
])

/* prettier-ignore-end */
